AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda for generating thumbnails from MP4 files

Resources:
    LambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: .
            Handler: app.handler
            Runtime: nodejs8.10